AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM Template to deploy a Lambda function that processes DynamoDB Stream records.

Resources:
  EventTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: EventTable
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttriuteName: version
          AttributeType: N
        - AttributeName: event
          AttriuteType: S
        - AttributeName: kind
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: version
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
